name: screenbuddy_mobile
description: "A mobile app that tracks screentime for the user."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  usage_stats: ^1.3.1
  fl_chart: ^1.0.0
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints_plus: ^3.3.0
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Fredoka
      fonts:
        - asset: fonts/Fredoka-Regular.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/buddies/circle/circleBlack.png
    - assets/buddies/circle/circleBlue.png
    - assets/buddies/circle/circleGreen.png
    - assets/buddies/circle/circleOrange.png
    - assets/buddies/circle/circlePink.png
    - assets/buddies/circle/circleRed.png
    - assets/buddies/circle/circleWhite.png
    - assets/buddies/hexagon/hexagonBlack.png
    - assets/buddies/hexagon/hexagonBlue.png
    - assets/buddies/hexagon/hexagonGreen.png
    - assets/buddies/hexagon/hexagonOrange.png
    - assets/buddies/hexagon/hexagonPink.png
    - assets/buddies/hexagon/hexagonRed.png
    - assets/buddies/hexagon/hexagonWhite.png
    - assets/buddies/pentagon/pentagonBlack.png
    - assets/buddies/pentagon/pentagonBlue.png
    - assets/buddies/pentagon/pentagonGreen.png
    - assets/buddies/pentagon/pentagonOrange.png
    - assets/buddies/pentagon/pentagonPink.png
    - assets/buddies/pentagon/pentagonRed.png
    - assets/buddies/pentagon/pentagonWhite.png
    - assets/buddies/square/squareBlack.png
    - assets/buddies/square/squareBlue.png
    - assets/buddies/square/squareGreen.png
    - assets/buddies/square/squareOrange.png
    - assets/buddies/square/squarePink.png
    - assets/buddies/square/squareRed.png
    - assets/buddies/square/squareWhite.png
    - assets/buddies/triangle/triangleBlack.png
    - assets/buddies/triangle/triangleBlue.png
    - assets/buddies/triangle/triangleGreen.png
    - assets/buddies/triangle/triangleOrange.png
    - assets/buddies/triangle/trianglePink.png
    - assets/buddies/triangle/triangleRed.png
    - assets/buddies/triangle/triangleWhite.png
